### ISSUE TITLE
fix http/https url issue

### ISSUE THREAD

**Issue by cchriste** [sci-visus/OpenVisusJS#12]
When the viewer lives under some https address, it can only access other servers that live under https, and vice versa (http can only access other http servers).

**Comment by spetruzza** [comment]
That probably has to do mixed content (http and https requests in the same page), which is a known security issue. The only solution I know is to configure the server to allow those kind of things, but it would not be a good idea...

**Comment by cchriste** [comment]
Is this a broad security setting or something in the webviewer itself? It would be worthwhile to just test it and make sure that's the issue.

**Comment by spetruzza** [comment]
Yes, in general you should not make requests to an http source from an https page, unless the server is configured to make an exception and/or your browser is old enough to allow that.
