### ISSUE TITLE
changing timesteps should maintain current viewpoint

### ISSUE THREAD

**Issue by cchriste** [sci-visus/OpenVisusJS#3]
It's also distracting that the old data disappears before the new data is shown.

Relevant for both 2d and 3d.

**Comment by spetruzza** [comment]
In the 3D viewer the viewpoint is maintained over time (try borg here https://goo.gl/B9kwVn)

In the 2D viewer probably it is an issue with OpenSeaDragon.

**Comment by cchriste** [comment]
Rather than fight with OSD, can we simply use 3d viewer for 2d datasets?

**Comment by cchriste** [comment]
Not sure when it was fixed, but this seems to work now (unless the viewpoint is hard-coded in the url).
