### ISSUE TITLE
In general, the UI seems confusing and doesn't offer feedback when a user performs an operation.

### ISSUE THREAD

**Issue by cchriste** [sci-visus/OpenVisusJS#5]
Somehow we need a "please wait" or "processing" or anything to indicate there is something happening. Also, some operations seem to never complete (for example, when resolution is just a little high, say 26 when viewing a slice of 2kbit1, and you click **View**) and then later something random happens, like the view updates (but not to 26).

**Comment by spetruzza** [comment]
Yes, we need to show track of (mainly) fetching operations with some loading bar...

**Comment by spetruzza** [comment]
I added a loading "animation" on top "status bar" that tells when streaming or rendering operation are going on

**Comment by cchriste** [comment]
The new UI seems to address these issues. Closing this issue.
