### ISSUE TITLE
Download doesn't work on Firefox 57

### ISSUE THREAD

**Issue by Twinklebear** [sci-visus/OpenVisusJS#8]
I tried to download a subsampling of Attila's [jet render](rawgit.com/sci-visus/visus_javascript/master/viewer.html?server=http%3A%2F%2Fmolniya.sci.utah.edu%2Fmod_visus%3F&dataset=topoart_big&field=data&slice=0&axis=2&time=0&vr=0&res=24&palette=&palette_min=0&palette_max=0&vp=1%2C0%2C0%2C0%2C0%2C1%2C0%2C0%2C0%2C0%2C1%2C0%2C0%2C0%2C-1%2C1&vd=1&q=1%2C0%2C0%2C0), however the download button doesn't seem to do anything on Firefox 57. In Chrome I was able to download the image ok.

**Comment by spetruzza** [comment]
fixed here aeb85cac4097533a0be61280ce2c9a92de6ed0f9
